server:
  port: 80
  servlet:
    context-path: /

spring:
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    #启用模板缓存
    cache: false
    #模板编码
    encoding: UTF-8
    mode: HTML5
    #前缀后缀
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html

  messages:
    basename: i18n.login

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/treehole?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      #建表更新
      ddl-auto: update
    show-sql: true

